### ISSUE TITLE
Add login feature

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/dicty-components-header-footer#2]

**Comment by wildlifehexagon** [comment]
Old DSC header/login code as reference point:

`import React, { Component, PropTypes } from 'react'
import Header from 'dicty-react-components/src/Header'
import HeaderLogo from 'dicty-react-components/src/HeaderLogo'
import HeaderLinks, { HeaderLink } from 'dicty-react-components/src/HeaderLinks'
import SearchBox from 'dicty-react-components/src/SearchBox'
import { Grid, Cell } from 'radium-grid'
import 'styles/core.scss'

export default class DictyHeader extends Component {
    displayName = 'navigation bar';
    static propTypes = {
        logo: PropTypes.object,
        auth: PropTypes.object,
        authActions: PropTypes.object
    }
    static defaultProps = {
        logo: {
            path: '/stockcenter/assets/dicty-logo.png',
            href: 'http://dictybase.org/'
        }
    }
    render() {
        const { logo, auth, authActions } = this.props
        return (
            <Header>
                <Grid smallCellWidth="1" mediumCellWidth="1" verticalAlign="bottom">
                    <Cell smallAlign="center" mediumAlign="center">
                        <HeaderLogo
                          path= { logo.path }
                          href= { logo.href }
                        />
                    </Cell>
                    <Cell>
                        <Grid cellWidth="1">
                            <Cell align="right" smallAlign="center" mediumAlign="center">
                                <HeaderLinks>
                                    <HeaderLink
                                      router
                                      to="/contact"
                                      name="Contact"
                                      iconClass="fa fa-envelope"
                                    />

                                    { auth.isAuthenticated ? (
                                            <HeaderLink
                                              router
                                              to="/my-dsc"
                                              name="My DSC"
                                              iconClass="fa fa-user"
                                            />
                                        ) : null
                                    }
                                    {
                                        auth.isAuthenticated ? (
                                            <HeaderLink
                                              onClick={ authActions.logoutUser }
                                              to="#"
                                              name="Logout"
                                              iconClass="fa fa-sign-out"
                                            />
                                        ) : (
                                            <HeaderLink
                                              router
                                              to="/login"
                                              name="Login"
                                              iconClass="fa fa-sign-in"
                                            />
                                        )
                                    }
                                </HeaderLinks>
                            </Cell>
                            <Cell>
                                <SearchBox />
                            </Cell>
                        </Grid>
                    </Cell>
                </Grid>
            </Header>
        )
    }
}

`

**Comment by cybersiddhu** [comment]
With this component the login link should be set similar to others 
```
<Header
   downloads="/downloads"
   info="/information"
   cite="/citation"
   login="/login" 
/>
```
The application should be decide to show it or not, something like this ..
```
{
   auth.isAuthenticated ? (
   <Header
      downloads="/downloads"
      info="/information"
      cite="/citation"
      login="/login" 
   />
    ) : (
  <Header
      downloads="/downloads"
      info="/information"
      cite="/citation"
   />         
  )
}
```
The `link` out should also be decided by the application, for example in case of  `dsc` app, it should come from a react-router object and should go to a login display component of that application.

And as a side note the login display component could become a standalone in the near future, need some clear abstraction.

**Comment by wildlifehexagon** [comment]
In the `feature/add-login-button` branch I updated the header to accept custom link props, similar to how it is done with the footer. This would allow for custom displaying of login/logout/my-dsc/etc links in the header. Won't merge this in yet since it would alter how other apps use the header -- will discuss in our next meeting.
